import React, { useState, useRef, useEffect } from "react";
import documentsIcon from "../../../assets/documents.svg";
import menuIcon from "../../../assets/menu.svg";
import responseIcon from "../../../assets/response.svg";
import shareIcon from "../../../assets/share.svg";
import thumbsDownIcon from "../../../assets/thumbs_down.svg";
import axios from "axios";
import { API_BASE_URL } from "../../../config";
import "./response.scss";
import Popup from "../popup/popup";

const Response = ({ response, chatId, conversationId, chats, setChats }) => {
  const [isPopupOpen, setIsPopupOpen] = useState(false);
  const [feedbackReaction, setFeedbackReaction] = useState("negative");
  const [feedbackResponse, setFeedbackResponse] = useState("");
  const popupRef = useRef(null);

  const isLoading = response === "Loading Response";

  const submitFeedback = () => {
    const requestBody = {
      conversationId: conversationId,
      chat_id: chatId,
      reaction: feedbackReaction,
      response: feedbackResponse,
    };

    const apiUrl = `${API_BASE_URL}/feedback?conversation-id=${conversationId}&chat-id=${chatId}`;
    axios
      .post(apiUrl, requestBody)
      .then((response) => {
        setFeedbackResponse("");
        const updatedChats = chats.map((chat) => {
          if (chat.chat_id === chatId) {
            return { ...chat, reaction: feedbackReaction };
          }
          return chat;
        });

        setChats(updatedChats);
      })
      .catch((error) => {
        console.error("Error:", error);
      });
  };

  const onFeedbackClick = (reaction) => {
    setFeedbackReaction(reaction);
    if (isPopupOpen) {
      setFeedbackResponse("");
    }
    setIsPopupOpen((prev) => !prev);
  };

  // Scroll into view when the popup is opened
  useEffect(() => {
    setIsPopupOpen(false); // Close popup
  }, [chatId, conversationId]);

  useEffect(() => {
    if (isPopupOpen && popupRef.current) {
      setTimeout(() => {
        popupRef.current.scrollIntoView({ behavior: "smooth", block: "start" });
      }, 0);
    }
  }, [isPopupOpen]);

  const showClausesPage = () => {
    window.open(
      `${window.location.origin}/conversation/${conversationId}/chat/${chatId}/referred-clauses`,
      "_blank"
    );
  };

  return (
    <div className="response_wrapper">
      <div className="response_section">
        <img src={responseIcon} alt="response icon" />
        <div className="text">
          {isLoading ? (
            <>
              {"Generating response"}
              <div className="loading_ellipsis"></div>
            </>
          ) : (
            "Generated by AI"
          )}
        </div>
        {!isLoading && <div className="line"></div>}
      </div>

      {!isLoading && (
        <>
          <div
            className="response_text"
            dangerouslySetInnerHTML={{
              __html: response?.replace(/\*\*(.*?)\*\*/g, "<b>$1</b>"),
            }}
          ></div>

          <div className="icon_wrapper">
            <div className={`icon_container ${isPopupOpen ? "active" : ""}`}>
              <img
                src={thumbsDownIcon}
                alt="thumbs down icon"
                onClick={() => onFeedbackClick("negative")}
              />
            </div>
            <div className="icon_container">
              <img src={shareIcon} alt="share icon" />
            </div>
            <div className="icon_container">
              <img
                src={documentsIcon}
                alt="documents icon"
                onClick={() => showClausesPage()}
              />
            </div>
            <div className="icon_container">
              <img src={menuIcon} alt="menu icon" />
            </div>
          </div>

          {isPopupOpen && (
            <Popup
              popupRef={popupRef}
              closePopup={() => setIsPopupOpen(false)}
              feedbackResponse={feedbackResponse}
              setFeedbackResponse={setFeedbackResponse}
              submitFeedback={submitFeedback}
            />
          )}
        </>
      )}
    </div>
  );
};

export default Response;
